name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - release/*
      - patch/*
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Free up disk space at start
        run: |
          sudo apt clean
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install project dependencies
        run: uv sync --locked --all-extras --dev

      - name: Check linting
        run: uv run task lint

      - name: Check formatting
        run: uv run task is-formatted

      - name: Test with pytest
        run: |
          uv run task force-cpu-torch
          uv run task extra-lib
          uv run task test
